### ISSUE TITLE
Tests fail due to error of HAPI FHIR test server

### ISSUE THREAD

**Issue by devmotion** [JuliaHealth/FHIRClient.jl#134]
Currently tests on the master branch fail with errors such as
```julia
 Got exception outside of a @test
  HTTP.Exceptions.StatusError(500, "GET", "/baseR4/Patient?given=Jason&family=Argonaut", HTTP.Messages.Response:
  """
  HTTP/1.1 500 Internal Server Error
  Server: nginx/1.18.0 (Ubuntu)
  Date: Sun, 26 Nov 2023 19:09:45 GMT
  Content-Type: application/fhir+json;charset=utf-8
  Transfer-Encoding: chunked
  Connection: keep-alive
  X-Powered-By: HAPI FHIR 6.9.5-SNAPSHOT/7e3c42549d/2023-09-09 REST Server (FHIR Server; FHIR 4.0.1/R4)
  X-Request-ID: 2phDCqTeMtgW24f4
  
  {
    "resourceType": "OperationOutcome",
    "text": {
      "status": "generated",
      "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td>HAPI-2223: Timer already cancelled.; nested exception is java.lang.IllegalStateException: Timer already cancelled.</td></tr></table></div>"
    },
    "issue": [ {
      "severity": "error",
      "code": "processing",
      "diagnostics": "HAPI-2223: Timer already cancelled.; nested exception is java.lang.IllegalStateException: Timer already cancelled."
    } ]
  }""")
  Stacktrace:
    [1] (::HTTP.ConnectionRequest.var"#connections#4"{HTTP.ConnectionRequest.var"#connections#1#5"{HTTP.TimeoutRequest.var"#timeouts#3"{HTTP.TimeoutRequest.var"#timeouts#1#4"{HTTP.ExceptionRequest.var"#exceptions#2"{HTTP.ExceptionRequest.var"#exceptions#1#3"{typeof(HTTP.StreamRequest.streamlayer)}}}}}})(req::HTTP.Messages.Request; proxy::Nothing, socket_type::Type, socket_type_tls::Type, readtimeout::Int64, connect_timeout::Int64, logerrors::Bool, logtag::Nothing, kw::Base.Pairs{Symbol, Union{Nothing, Int64}, Tuple{Symbol, Symbol, Symbol}, NamedTuple{(:iofunction, :decompress, :verbose), Tuple{Nothing, Nothing, Int64}}})
...
```

It seems the test failures are caused by problems with the public FHIR server and can be reproduced e.g. by going to https://hapi.fhir.org/baseR4/Patient?given=Jason&family=Argonaut.

Ref https://github.com/hapifhir/hapi-fhir/issues/5479
Ref https://github.com/hapifhir/hapi-fhir/issues/5485

**Comment by DilumAluthge** [comment]
As a short-term workaround, can we find another public test server to use?

**Comment by DilumAluthge** [comment]
The HAPI [Getting Help](https://github.com/hapifhir/hapi-fhir/wiki/Getting-Help) page mentions a Google Group. Maybe we should post there to ask about the error?

I'm guessing that responses will likely be delayed due to the holiday.

**Comment by devmotion** [comment]
Based on the Github issues and [this message](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/What.20is.20a.20nice.20FHIR.20test.20server.20that.20is.20available.20to.20test.3F/near/404086819) in the chat, I think the HAPI FHIR responsibles are aware of the problem. According to the chat, https://server.fire.ly/r4 still works but apparently otherwise https://confluence.hl7.org/display/FHIR/Public+Test+Servers is quite outdated.
